### ISSUE TITLE
kube-dns failed to start

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/dns#138]
kube-dns on master branch failed to start:

```sh
# kubectl logs kube-dns-1476438210-rzf6r -c kubedns
...
I0814 09:53:28.164431     104 server.go:130] Setting up Healthz Handler (/readiness)
I0814 09:53:28.164449     104 server.go:135] Setting up cache handler (/cache)
I0814 09:53:28.164455     104 server.go:146] Setting up pprof handler (/debug/pprof)
panic: http: multiple registrations for /debug/pprof/

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x2022de0, 0x1713f52, 0xd, 0x1fc3120, 0x1780750)
	/usr/local/go/src/net/http/server.go:2254 +0x610
net/http.(*ServeMux).HandleFunc(0x2022de0, 0x1713f52, 0xd, 0x1780750)
	/usr/local/go/src/net/http/server.go:2286 +0x55
net/http.HandleFunc(0x1713f52, 0xd, 0x1780750)
	/usr/local/go/src/net/http/server.go:2298 +0x4b
k8s.io/dns/cmd/kube-dns/app.(*KubeDNSServer).setupHandlers(0xc420014b40)
	/go/src/k8s.io/dns/cmd/kube-dns/app/server.go:147 +0x1a5
k8s.io/dns/cmd/kube-dns/app.(*KubeDNSServer).Run(0xc420014b40)
	/go/src/k8s.io/dns/cmd/kube-dns/app/server.go:119 +0x7b
main.main()
	/go/src/k8s.io/dns/cmd/kube-dns/dns.go:51 +0x2f8
```

The problem is introduced in #128.  we have imported "net/http/pprof" in cmd/kube-dns/app/options/options.go, which have already registered handlers for `/debug/pprof/`.

**Comment by MrHohn** [comment]
I'm surprised that CI didn't catch this.

cc @allencloud @bowei

**Comment by feiskyer** [comment]
@MrHohn Is possible to add e2e tests for kube-dns?

**Comment by bowei** [comment]
I'm surprised as well. The kube-dns submit travis does include an e2e test, we need to investigate why this was not caught...

**Comment by andyxning** [comment]
It turns out that there is a race condition for kube-dns e2e test. As the kube-dns service is running in background and we only wait for the dns service(`10053`) to be ready before doing a query, there are chances that kube-dns has not register the http services(pprof and health check) before kube-dns e2e ginkgo test do a request.

What kube-dns e2e test should do is to also wait for health check port to be available before doing a query.

#145  is desired to fix this.
