### ISSUE TITLE
can add PTR & A record support for pod in deployment?

### ISSUE THREAD

**Issue by SchoIsles** [kubernetes/dns#164]
In my case, some services(mysql) is out of k8s cluster,  applications in cluster access the service need a authorization.

With pod's ip is not static and continuously, cant't grant privileges to a CIDR subnet.
So I wan't to grant to a wild domain, looks like `*.<service>.<namespace>.svc.<domain>`, all pod in this service will be granted by dns reverse.

now I tested on headless service & statefulset, all pod with name `<set-name>-{id}` has an A record, and this pod's ip has a PTR record.

But pod in deployments doesn't have a hostname field, can't be resolved

**Comment by thockin** [comment]
In general pods in a Deployment are considered fungible, and as such do not have DNS.  We can't do the PTR based on Service name because a pod can be "in" multiple Services but DNS says you can only have one PTR record.  We could do it and just pick one at random - people who use multiple overlapping services would not be able to rely on it.

An alternative model would be for you to do a forward (A) lookup of the "allowed" DNS name and check whether the client IP is part of the returned set.  I don't know of anything that operates that way, though.

The way network policy operates is that a controller watches for pods to change, and then updates teh configs based on that.  More complicated and dynamic, but correct and flexible.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/dns] can add PTR & ..." ]
> We can't do the PTR based on Service name because a pod can be "in" 
> multiple Services but DNS says you can only have one PTR record.

I don't think this is true. Multiple records are allowed and I'm not aware of an 
RFC that says there can only be one for 1 name for a PTR...

/Miek

--
Miek Gieben

**Comment by thockin** [comment]
Far be it from me to challenge @miekg on DNS - it is in fact ALLOWED, but it seems generally discouraged (many sites and blog posts warning not to do it).  The arguments seem relatively weak, but DNS compatibility has repeatedly proven more complex than I expect it to be.
