### ISSUE TITLE
How can I create dns records manually?

### ISSUE THREAD

**Issue by Win32Sector** [kubernetes/dns#402]
Hi all!
I have microservice, it deployed with daemonSet on windows nodes in kubernetes cluster 1.18.6 on AKS.
I have another microservice it deployed with daemonSet on windows nodes too.
And I need communicate from first microservice on one node to second microservice on the same node.

Host networking and topologyKeys don't work in this case.

I need, when pods of second microservice start, create dns record for this pod, for example, 

microservicename-nodename.cluster.local

But I don't find, how can I manually add records to coredns. 

Can anybody help me with it?

**Comment by dwradcliffe** [comment]
Have you read this? https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by prameshj** [comment]
There isn't a way to manually create DNS records into CoreDNS or kube-dns. You would need to configure the service and endpoints appropriately and the DNS records will be generated as per the spec in https://github.com/kubernetes/dns/blob/master/docs/specification.md

The syntax you are looking for - "microservicename-nodename.cluster.local" does not include the namespace, so that does not get created with the spec. This might help - https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/

But it needs to be in CoreDNS, not node-local-dns.
