### ISSUE TITLE
Use upstream CoreDNS for NodeLocal Cache

### ISSUE THREAD

**Issue by Pryz** [kubernetes/dns#410]
Hi there,

The current NodeLocal cache implementation is a custom binaries based on CoreDNS. The current design makes it hard to manage when you have a custom Coredns configuration. 

I'm wondering if people are interested in been able to just use the upstream CoreDNS binary (or bring-your-own coredns) while still using the "cache binary" to setup the 169.254 network interface as well as the proper iptables rule ?

Maybe I'm missing something but it looks to me that a simple entrypoint could do the job of setting up the network before starting coredns.

Thanks

**Comment by prameshj** [comment]
one way to achieve this is by implementing node-cache as a coreDNS plugin. @yannh was working on this, IIRC.

**Comment by yannh** [comment]
Thanks @prameshj for the mention, @Pryz :wave: https://github.com/contentful-labs/coredns-nodecache  is what I/we've been working on and are using. Since it is a plugin, it allows you to use the Corefile to configure CoreDNS and nodecache. Happy to know whether it would work for your use-case, or what your solution would look like if not.

I can't help but think that this routing should be handled by Kubernetes itself and that Daemonsets should have a DNS like "node-local.daemonset.cluster.local" and an IP assigned.

**Comment by Pryz** [comment]
Hi @yannh, we ended up using a similar system but based on the upstream CoreDNS.

We basically took the upstream CoreDNS and adding our own entrypoint in the Docker image to set the proper iptables rules when the POD starts. The configuration is managed via a ConfigMap (with the proper binding configuration on `169.254.20.10`.

The rest is pretty standards to CoreDNS. Nothing custom to compile.

We have been running that since few months in Production with pretty good results so far.

**Comment by prameshj** [comment]
glad to hear that is working well, Julien.

> I can't help but think that this routing should be handled by Kubernetes itself and that Daemonsets should have a DNS like "node-local.daemonset.cluster.local" and an IP assigned.

The custom iptables solution only works for iptables kube-proxy mode. CNI might be a good place to put this if it becomes more standard and there are multiple services using a similar routing solution.

/close
