### ISSUE TITLE
NodeLocalDNS has i/o timeout when connecting to kube-dns-upstream

### ISSUE THREAD

**Issue by nontster** [kubernetes/dns#443]
Hi, 

I got errors in NodeLocalDNS log from 1 of 8 worker node when enable NodeLocalDNS.

the error pattern is, 
```
<some domain>. A: dial tcp <kube-dns-upstream IP>:53: i/o timeout
<another domain>. AAAA: dial tcp <kube-dns-upstream IP>:53: i/o timeout
```

Is that normal and how to check ?

Thanks, 

Nont

**Comment by prameshj** [comment]
What environment is this on? Most likely this is due to the kube-dns upstream not responding within 2s - nodelocaldns (which uses coreDNS) has a 2s read timeout... so if kube-dns takes longer, you can see this log.

If you are on GKE, you can see more details here - https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache#nodelocaldns_timeout_errors

**Comment by prameshj** [comment]
please reopen if this is not the issue.
