### ISSUE TITLE
Lack of documentation surrounding image release history of node-local-dns

### ISSUE THREAD

**Issue by ndombroski** [kubernetes/dns#513]
Hi everyone, 

I've noticed that there is no official version release history of the node-local images at k8s.gcr.io/dns/k8s-dns-node-cache

I've been attempting to find the changes in v1.21.1 (which appears to be the latest image version version according to https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml), but I cannot find any changelog documenting the release history of this image. 

It would very helpful to have official documentation of the versions available at k8s.gcr.io/dns/k8s-dns-node-cache, when they were released, and which commits to this repository are included in them.

**Comment by yogeek** [comment]
Hi !

I just upgrade my K8S cluster to 1.22 and took a look at all the addons to check updates and have exactly the same concern.

One additional information that could help in addition to the release notes is mentioning if there is a compatibility matrix between Kubernetes version and node-local-cache-dns version please ?
For example : Is upgrading my current `dns/k8s-dns-node-cache:1.19.0` to a newer tag is mandatory to make it work with K8S 1.22 ?

**Comment by dpasiukevich** [comment]
Yep, I will start making a release for each new tag.

There's no compatibility matrix. And as I can see from the PR history at least from `1.19.0` tag there are no changes that would _force_ you to upgrade the nodelocaldns with newer K8S versions
But it's worth keeping nodelocaldns closer to the newest versions as there are mainly vulnerability fixed in underlying base image.
