### ISSUE TITLE
Getting UnkownHostException from SpringBoot Microservice running on top of kubernetes

### ISSUE THREAD

**Issue by maulikprajapati** [kubernetes/dns#637]
*What happened:*
My application is running on top of kubernetes 1.26. 
I am getting sometime (not frequent) an exception from Some microservices (spring-boot 2.7.RELEASE using base image
eclipse-temurin:17-jre) trying to request another service through k8s servicie name. telling me UnknownHostException..
That means the service which initiating the request is not able to resolve hostname.

What you expected to happen:
I am expecting to not see this exception and all calls are DNS resolvable.

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

I Tried to make a script which run nslookup command 10000 time and i did not get any error and all calls to service were
resolved successfully.
This issue happen from today only where there is no change related dns .

**Comment by hinst** [comment]
I have been observing `UnknownHostException` in Docker using `eclipse-temurin:17-jdk`. I believe the error is caused by the Docker image. 

If you look at the version history of the Docker image https://hub.docker.com/layers/library/eclipse-temurin/17-jdk/images/sha256-3f4fd8f15f322224c64e6028a2fe6ae2c648904ff9b5b8fd30f785974adab9da?context=explore you will notice that the image gets updated frequently. Right now it shows LAST PUSHED 8 days ago. I believe a buggy version of the image got pushed at some point
