### ISSUE TITLE
[Question] Documentation on contributing to dns

### ISSUE THREAD

**Issue by alok87** [kubernetes/dns#92]
Is there any document telling how to setup kube dns locally for contribution and debugging ?

**Comment by cmluciano** [comment]
The makefile does allow you to run the tests locally. You can also use it to generate containers that can be launched in the cluster. Since install tools are omnipresent, it is difficult to doc how to launch them on each tool.

It might be feasible to document it for things like kubeadm though. cc @k8s-mirror-cluster-lifecycle-misc

**Comment by alok87** [comment]
@cmluciano can we use minikube cluster to deploy locally build images of dns ? Does it require us to keep pushing to dockerhub ?

**Comment by cmluciano** [comment]
I admit that I have not tried it, but it does seem feasible https://github.com/kubernetes/minikube/blob/master/docs/addons.md .

**Comment by bowei** [comment]
You can start your own copy of the DNS service by instantiating a custom YAML and changing the names + labels. It's just a standard Kubernetes service.

**Comment by bowei** [comment]
@alok87 could you open two issues: 1) re: better documentation on debugging and 2) a separate one on how to contribute?

Thanks

**Comment by alok87** [comment]
@bowei Done https://github.com/kubernetes/dns/issues/99 https://github.com/kubernetes/dns/issues/100
Closing this issue
